### PR TITLE
availability cleanup

### PR DESCRIPTION
**Pull request by czervenka**
Proposal for availability data structure cleanup

The data structure will not be prepared for possible future enhancements but it will be cleaner and more readable.

Hotel data structure should point to the new Availability object after the change.

We also need to change
- read API
- write API
- Explorer
- anything else?

### CODE REVIEW

**Comment by JirkaChadima** [comment]
Just one question: why now and not a month before when we were implementing this?

I think this actually affects only wt-read-api and wt-write-api. Read API is already pulling the data one level up, so the explorer is unaffected. Maybe it affects wt-js-libs.

Anyway definitely not something we're doing before the hackathon

**Comment by hynek-urban** [comment]
I like this. Aside from the mentioned apis, wt-booking-api is also affected and so is wt-fixtures.

**Comment by hynek-urban** [comment]
There is one more thing this affects: data in playground and demo. We should re-deploy them.

**Comment by JirkaChadima** [comment]
> There is one more thing this affects: data in playground and demo. We should re-upload them.

I think we should actually redeploy the playground env after the hackathon (or maybe do it every month or so)... It's going to be a good opportunity to put some process for that in place (setting up future dates, how to inform everybody etc.)

**Pull request merged**
